browser=chrome
headless=false
baseUrlWalletHub=https://wallethub.com
wallethubProfileUrl=https://wallethub.com/profile/13732055i

# WalletHub login (use your created "light" account)
wh.email=YOUR_EMAIL
wh.password=YOUR_PASSWORD

# Facebook (keep changeable)
fb.email=YOUR_FB_EMAIL
fb.password=YOUR_FB_PASSWORD