browser=chrome
headless=false
baseUrlWalletHub=https://wallethub.com
wallethubProfileUrl=https://wallethub.com/profile/test-insurance-company-13732055i

# WalletHub login (use your created "light" account)
wh.email=asadiqulsaimon3@gmail.com
wh.password=Wallet!@098

# Facebook (keep changeable)
fb.email=your-email
fb.password=your-password
close.browser=false
